using TaxFlow.Core.Entities;
using TaxFlow.Core.Interfaces;
using TaxFlow.Core.Exceptions;
using Microsoft.Extensions.Logging;
using System.Text;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;

namespace TaxFlow.Infrastructure.Services.Reporting;

/// <summary>
/// Advanced reporting service with QuestPDF and ClosedXML
/// </summary>
public class ReportingService : IReportingService
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly ILogger<ReportingService> _logger;

    static ReportingService()
    {
        // Configure QuestPDF license for community use
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public ReportingService(
        IUnitOfWork unitOfWork,
        ILogger<ReportingService> logger)
    {
        _unitOfWork = unitOfWork;
        _logger = logger;
    }

    public async Task<byte[]> GenerateInvoicePdfAsync(
        Guid invoiceId,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var invoice = await _unitOfWork.Invoices.GetWithDetailsAsync(invoiceId);
            if (invoice == null)
                throw new DocumentNotFoundException(
                    $"Invoice with ID {invoiceId} not found",
                    invoiceId.ToString(),
                    "Invoice");

            _logger.LogInformation("Generating PDF for invoice {InvoiceNumber}", invoice.InvoiceNumber);

            var pdfBytes = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(10).FontFamily("Arial"));

                    page.Header()
                        .AlignCenter()
                        .Text("فاتورة إلكترونية - Electronic Invoice")
                        .FontSize(20)
                        .Bold()
                        .FontColor(Colors.Blue.Darken3);

                    page.Content()
                        .Column(column =>
                        {
                            column.Spacing(10);

                            // Invoice Information
                            column.Item().Row(row =>
                            {
                                row.RelativeItem().Column(col =>
                                {
                                    col.Item().Text($"رقم الفاتورة: {invoice.InvoiceNumber}").Bold();
                                    col.Item().Text($"التاريخ: {invoice.DateTimeIssued:yyyy-MM-dd HH:mm}");
                                    col.Item().Text($"نوع المستند: {invoice.DocumentType}");
                                });

                                row.RelativeItem().Column(col =>
                                {
                                    col.Item().AlignRight().Text($"Invoice: {invoice.InvoiceNumber}").Bold();
                                    col.Item().AlignRight().Text($"Date: {invoice.DateTimeIssued:yyyy-MM-dd HH:mm}");
                                    col.Item().AlignRight().Text($"Type: {invoice.DocumentType}");
                                });
                            });

                            // Customer Information
                            if (invoice.Customer != null)
                            {
                                column.Item().PaddingTop(15).Element(CustomerSection);
                            }

                            // Line Items Table
                            column.Item().PaddingTop(15).Element(InvoiceLinesTable);

                            // Totals
                            column.Item().PaddingTop(15).Element(TotalsSection);

                            // ETA Information
                            if (!string.IsNullOrEmpty(invoice.EtaLongId))
                            {
                                column.Item().PaddingTop(15).Element(EtaSection);
                            }

                            // Signature Information
                            if (!string.IsNullOrEmpty(invoice.Signature))
                            {
                                column.Item().PaddingTop(10).Element(SignatureSection);
                            }
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Generated by TaxFlow Enterprise - ");
                            x.Span(DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
                        })
                        .FontSize(8)
                        .FontColor(Colors.Grey.Darken2);
                });

                void CustomerSection(IContainer container)
                {
                    container.Background(Colors.Grey.Lighten3).Padding(10).Column(column =>
                    {
                        column.Item().Text("معلومات العميل - Customer Information").Bold().FontSize(12);
                        column.Item().PaddingTop(5).Row(row =>
                        {
                            row.RelativeItem().Text($"الاسم: {invoice.Customer!.NameAr}");
                            row.RelativeItem().Text($"Name: {invoice.Customer.NameEn}");
                        });
                        column.Item().Row(row =>
                        {
                            row.RelativeItem().Text($"رقم التسجيل الضريبي: {invoice.Customer.TaxRegistrationNumber}");
                            row.RelativeItem().Text($"البريد: {invoice.Customer.Email}");
                        });
                    });
                }

                void InvoiceLinesTable(IContainer container)
                {
                    container.Table(table =>
                    {
                        // Define columns
                        table.ColumnsDefinition(columns =>
                        {
                            columns.ConstantColumn(30);  // #
                            columns.RelativeColumn(3);   // Description
                            columns.RelativeColumn(1);   // Quantity
                            columns.RelativeColumn(1);   // Unit Price
                            columns.RelativeColumn(1);   // Discount
                            columns.RelativeColumn(1);   // Net
                            columns.RelativeColumn(1);   // Tax
                            columns.RelativeColumn(1);   // Total
                        });

                        // Header
                        table.Header(header =>
                        {
                            header.Cell().Element(HeaderCell).Text("#");
                            header.Cell().Element(HeaderCell).Text("الوصف / Description");
                            header.Cell().Element(HeaderCell).Text("الكمية / Qty");
                            header.Cell().Element(HeaderCell).Text("السعر / Price");
                            header.Cell().Element(HeaderCell).Text("الخصم / Disc");
                            header.Cell().Element(HeaderCell).Text("الصافي / Net");
                            header.Cell().Element(HeaderCell).Text("الضريبة / Tax");
                            header.Cell().Element(HeaderCell).Text("الإجمالي / Total");

                            static IContainer HeaderCell(IContainer container)
                            {
                                return container
                                    .Background(Colors.Blue.Darken3)
                                    .Padding(5)
                                    .DefaultTextStyle(x => x.FontColor(Colors.White).Bold().FontSize(8));
                            }
                        });

                        // Rows
                        int lineNumber = 1;
                        foreach (var line in invoice.Lines)
                        {
                            table.Cell().Element(DataCell).Text(lineNumber.ToString());
                            table.Cell().Element(DataCell).Text(line.Description);
                            table.Cell().Element(DataCell).AlignRight().Text(line.Quantity.ToString("N2"));
                            table.Cell().Element(DataCell).AlignRight().Text(line.UnitPrice.ToString("N2"));
                            table.Cell().Element(DataCell).AlignRight().Text(line.Discount.ToString("N2"));
                            table.Cell().Element(DataCell).AlignRight().Text(line.NetAmount.ToString("N2"));
                            table.Cell().Element(DataCell).AlignRight().Text(line.TotalTaxAmount.ToString("N2"));
                            table.Cell().Element(DataCell).AlignRight().Text(line.TotalAmount.ToString("N2"));
                            lineNumber++;
                        }

                        static IContainer DataCell(IContainer container)
                        {
                            return container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).Padding(5).DefaultTextStyle(x => x.FontSize(9));
                        }
                    });
                }

                void TotalsSection(IContainer container)
                {
                    container.AlignRight().Column(column =>
                    {
                        column.Item().Row(row =>
                        {
                            row.ConstantItem(150).Text("الإجمالي قبل الخصم:").Bold();
                            row.ConstantItem(100).AlignRight().Text($"{invoice.TotalSalesAmount:N2} EGP");
                        });
                        column.Item().Row(row =>
                        {
                            row.ConstantItem(150).Text("الخصم الكلي:");
                            row.ConstantItem(100).AlignRight().Text($"{invoice.TotalDiscountAmount:N2} EGP");
                        });
                        column.Item().Row(row =>
                        {
                            row.ConstantItem(150).Text("الصافي:");
                            row.ConstantItem(100).AlignRight().Text($"{invoice.NetAmount:N2} EGP");
                        });
                        column.Item().Row(row =>
                        {
                            row.ConstantItem(150).Text("ضريبة القيمة المضافة:").Bold();
                            row.ConstantItem(100).AlignRight().Text($"{invoice.TotalTaxAmount:N2} EGP");
                        });
                        column.Item().PaddingTop(5).Row(row =>
                        {
                            row.ConstantItem(150).Text("الإجمالي النهائي:").Bold().FontSize(12).FontColor(Colors.Green.Darken3);
                            row.ConstantItem(100).AlignRight().Text($"{invoice.TotalAmount:N2} EGP").Bold().FontSize(12).FontColor(Colors.Green.Darken3);
                        });
                    });
                }

                void EtaSection(IContainer container)
                {
                    container.Background(Colors.Green.Lighten4).Padding(10).Column(column =>
                    {
                        column.Item().Text("معلومات مصلحة الضرائب - ETA Information").Bold();
                        column.Item().PaddingTop(5).Text($"ETA Long ID: {invoice.EtaLongId}");
                        column.Item().Text($"Status: {invoice.Status}");
                        if (invoice.SubmittedAt.HasValue)
                        {
                            column.Item().Text($"Submitted: {invoice.SubmittedAt.Value:yyyy-MM-dd HH:mm}");
                        }
                    });
                }

                void SignatureSection(IContainer container)
                {
                    container.Background(Colors.Blue.Lighten4).Padding(10).Column(column =>
                    {
                        column.Item().Text("التوقيع الرقمي - Digital Signature").Bold();
                        column.Item().PaddingTop(5).Text($"Signed: {invoice.SignedAt?.ToString("yyyy-MM-dd HH:mm")}");
                        column.Item().Text("Signature: CADES-BES Format").FontSize(8);
                    });
                }
            }).GeneratePdf();

            _logger.LogInformation("PDF generated successfully for invoice {InvoiceNumber}", invoice.InvoiceNumber);
            return pdfBytes;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating invoice PDF for {InvoiceId}", invoiceId);
            throw;
        }
    }

    public async Task<byte[]> GenerateReceiptPdfAsync(
        Guid receiptId,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var receipt = await _unitOfWork.Receipts.GetWithDetailsAsync(receiptId);
            if (receipt == null)
                throw new DocumentNotFoundException(
                    $"Receipt with ID {receiptId} not found",
                    receiptId.ToString(),
                    "Receipt");

            _logger.LogInformation("Generating PDF for receipt {ReceiptNumber}", receipt.ReceiptNumber);

            var pdfBytes = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A5);
                    page.Margin(1, Unit.Centimetre);
                    page.PageColor(Colors.White);

                    page.Header()
                        .AlignCenter()
                        .Text("إيصال بيع - Sales Receipt")
                        .FontSize(18)
                        .Bold()
                        .FontColor(Colors.Blue.Darken3);

                    page.Content()
                        .Column(column =>
                        {
                            column.Spacing(8);

                            // Receipt info
                            column.Item().AlignCenter().Text($"رقم الإيصال: {receipt.ReceiptNumber}").Bold();
                            column.Item().AlignCenter().Text($"التاريخ: {receipt.DateTimeIssued:yyyy-MM-dd HH:mm}");

                            // Items
                            column.Item().PaddingTop(10).Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.RelativeColumn(3);
                                    columns.RelativeColumn(1);
                                    columns.RelativeColumn(1);
                                    columns.RelativeColumn(1);
                                });

                                table.Header(header =>
                                {
                                    header.Cell().Text("الصنف").Bold();
                                    header.Cell().AlignRight().Text("الكمية").Bold();
                                    header.Cell().AlignRight().Text("السعر").Bold();
                                    header.Cell().AlignRight().Text("الإجمالي").Bold();
                                });

                                foreach (var line in receipt.Lines)
                                {
                                    table.Cell().Text(line.Description);
                                    table.Cell().AlignRight().Text(line.Quantity.ToString("N0"));
                                    table.Cell().AlignRight().Text(line.UnitPrice.ToString("N2"));
                                    table.Cell().AlignRight().Text(line.TotalAmount.ToString("N2"));
                                }
                            });

                            // Totals
                            column.Item().PaddingTop(10).BorderTop(1).PaddingTop(5).AlignRight().Column(totals =>
                            {
                                totals.Item().Text($"الصافي: {receipt.NetAmount:N2} EGP");
                                totals.Item().Text($"الضريبة: {receipt.TotalTaxAmount:N2} EGP");
                                totals.Item().Text($"الإجمالي: {receipt.TotalAmount:N2} EGP").Bold().FontSize(14);
                                totals.Item().PaddingTop(5).Text($"طريقة الدفع: {receipt.PaymentMethod}");
                            });
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text("شكراً لتعاملكم معنا - Thank you!")
                        .FontSize(10);
                });
            }).GeneratePdf();

            return pdfBytes;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating receipt PDF for {ReceiptId}", receiptId);
            throw;
        }
    }

    public async Task<byte[]> ExportInvoicesToExcelAsync(
        InvoiceExportOptions options,
        CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Exporting invoices to Excel");

            var invoices = await _unitOfWork.Invoices.GetAllAsync();

            // Apply filters
            if (options.StartDate.HasValue)
                invoices = invoices.Where(i => i.DateTimeIssued >= options.StartDate.Value);

            if (options.EndDate.HasValue)
                invoices = invoices.Where(i => i.DateTimeIssued <= options.EndDate.Value);

            if (!string.IsNullOrEmpty(options.Status))
                invoices = invoices.Where(i => i.Status.ToString() == options.Status);

            if (options.CustomerId.HasValue)
                invoices = invoices.Where(i => i.CustomerId == options.CustomerId.Value);

            var invoiceList = invoices.ToList();

            using var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Invoices");

            // Header
            worksheet.Cell(1, 1).Value = "Invoice Number";
            worksheet.Cell(1, 2).Value = "Date";
            worksheet.Cell(1, 3).Value = "Customer";
            worksheet.Cell(1, 4).Value = "Tax Registration";
            worksheet.Cell(1, 5).Value = "Document Type";
            worksheet.Cell(1, 6).Value = "Total Sales";
            worksheet.Cell(1, 7).Value = "Discount";
            worksheet.Cell(1, 8).Value = "Net Amount";
            worksheet.Cell(1, 9).Value = "Tax Amount";
            worksheet.Cell(1, 10).Value = "Total Amount";
            worksheet.Cell(1, 11).Value = "Status";
            worksheet.Cell(1, 12).Value = "ETA Long ID";

            // Style header
            var headerRange = worksheet.Range(1, 1, 1, 12);
            headerRange.Style.Font.Bold = true;
            headerRange.Style.Fill.BackgroundColor = XLColor.LightBlue;
            headerRange.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

            // Data rows
            int row = 2;
            foreach (var invoice in invoiceList)
            {
                worksheet.Cell(row, 1).Value = invoice.InvoiceNumber;
                worksheet.Cell(row, 2).Value = invoice.DateTimeIssued.ToString("yyyy-MM-dd");
                worksheet.Cell(row, 3).Value = invoice.Customer?.NameEn ?? "";
                worksheet.Cell(row, 4).Value = invoice.Customer?.TaxRegistrationNumber ?? "";
                worksheet.Cell(row, 5).Value = invoice.DocumentType.ToString();
                worksheet.Cell(row, 6).Value = invoice.TotalSalesAmount;
                worksheet.Cell(row, 7).Value = invoice.TotalDiscountAmount;
                worksheet.Cell(row, 8).Value = invoice.NetAmount;
                worksheet.Cell(row, 9).Value = invoice.TotalTaxAmount;
                worksheet.Cell(row, 10).Value = invoice.TotalAmount;
                worksheet.Cell(row, 11).Value = invoice.Status.ToString();
                worksheet.Cell(row, 12).Value = invoice.EtaLongId ?? "";

                row++;
            }

            // Format currency columns
            worksheet.Column(6).Style.NumberFormat.Format = "#,##0.00";
            worksheet.Column(7).Style.NumberFormat.Format = "#,##0.00";
            worksheet.Column(8).Style.NumberFormat.Format = "#,##0.00";
            worksheet.Column(9).Style.NumberFormat.Format = "#,##0.00";
            worksheet.Column(10).Style.NumberFormat.Format = "#,##0.00";

            // Auto-fit columns
            worksheet.Columns().AdjustToContents();

            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            return stream.ToArray();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error exporting invoices to Excel");
            throw;
        }
    }

    public async Task<byte[]> ExportReceiptsToExcelAsync(
        ReceiptExportOptions options,
        CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Exporting receipts to Excel");

            var receipts = await _unitOfWork.Receipts.GetAllAsync();

            // Apply filters
            if (options.StartDate.HasValue)
                receipts = receipts.Where(r => r.DateTimeIssued >= options.StartDate.Value);

            if (options.EndDate.HasValue)
                receipts = receipts.Where(r => r.DateTimeIssued <= options.EndDate.Value);

            if (!string.IsNullOrEmpty(options.PaymentMethod))
                receipts = receipts.Where(r => r.PaymentMethod == options.PaymentMethod);

            var receiptList = receipts.ToList();

            using var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Receipts");

            // Header
            worksheet.Cell(1, 1).Value = "Receipt Number";
            worksheet.Cell(1, 2).Value = "Date";
            worksheet.Cell(1, 3).Value = "Net Amount";
            worksheet.Cell(1, 4).Value = "Tax Amount";
            worksheet.Cell(1, 5).Value = "Total Amount";
            worksheet.Cell(1, 6).Value = "Payment Method";
            worksheet.Cell(1, 7).Value = "Terminal";
            worksheet.Cell(1, 8).Value = "Status";

            var headerRange = worksheet.Range(1, 1, 1, 8);
            headerRange.Style.Font.Bold = true;
            headerRange.Style.Fill.BackgroundColor = XLColor.LightGreen;
            headerRange.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

            int row = 2;
            foreach (var receipt in receiptList)
            {
                worksheet.Cell(row, 1).Value = receipt.ReceiptNumber;
                worksheet.Cell(row, 2).Value = receipt.DateTimeIssued.ToString("yyyy-MM-dd HH:mm");
                worksheet.Cell(row, 3).Value = receipt.NetAmount;
                worksheet.Cell(row, 4).Value = receipt.TotalTaxAmount;
                worksheet.Cell(row, 5).Value = receipt.TotalAmount;
                worksheet.Cell(row, 6).Value = receipt.PaymentMethod;
                worksheet.Cell(row, 7).Value = receipt.TerminalId ?? "";
                worksheet.Cell(row, 8).Value = receipt.Status.ToString();
                row++;
            }

            worksheet.Column(3).Style.NumberFormat.Format = "#,##0.00";
            worksheet.Column(4).Style.NumberFormat.Format = "#,##0.00";
            worksheet.Column(5).Style.NumberFormat.Format = "#,##0.00";
            worksheet.Columns().AdjustToContents();

            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            return stream.ToArray();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error exporting receipts to Excel");
            throw;
        }
    }

    public async Task<byte[]> GenerateTaxSummaryReportAsync(
        TaxSummaryOptions options,
        CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Generating tax summary report");

            var invoices = await _unitOfWork.Invoices.GetAllAsync();
            var filteredInvoices = invoices
                .Where(i => i.DateTimeIssued >= options.StartDate && i.DateTimeIssued <= options.EndDate)
                .ToList();

            var receipts = await _unitOfWork.Receipts.GetAllAsync();
            var filteredReceipts = receipts
                .Where(r => r.DateTimeIssued >= options.StartDate && r.DateTimeIssued <= options.EndDate)
                .ToList();

            using var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Tax Summary");

            // Title
            worksheet.Cell(1, 1).Value = "Tax Summary Report";
            worksheet.Cell(1, 1).Style.Font.Bold = true;
            worksheet.Cell(1, 1).Style.Font.FontSize = 16;

            worksheet.Cell(2, 1).Value = $"Period: {options.StartDate:yyyy-MM-dd} to {options.EndDate:yyyy-MM-dd}";

            // Invoice Summary
            worksheet.Cell(4, 1).Value = "B2B Invoices Summary";
            worksheet.Cell(4, 1).Style.Font.Bold = true;

            worksheet.Cell(5, 1).Value = "Total Invoices:";
            worksheet.Cell(5, 2).Value = filteredInvoices.Count;

            worksheet.Cell(6, 1).Value = "Total Net Amount:";
            worksheet.Cell(6, 2).Value = filteredInvoices.Sum(i => i.NetAmount);
            worksheet.Cell(6, 2).Style.NumberFormat.Format = "#,##0.00";

            worksheet.Cell(7, 1).Value = "Total Tax Amount:";
            worksheet.Cell(7, 2).Value = filteredInvoices.Sum(i => i.TotalTaxAmount);
            worksheet.Cell(7, 2).Style.NumberFormat.Format = "#,##0.00";

            worksheet.Cell(8, 1).Value = "Total Gross Amount:";
            worksheet.Cell(8, 2).Value = filteredInvoices.Sum(i => i.TotalAmount);
            worksheet.Cell(8, 2).Style.NumberFormat.Format = "#,##0.00";

            // Receipt Summary
            worksheet.Cell(10, 1).Value = "B2C Receipts Summary";
            worksheet.Cell(10, 1).Style.Font.Bold = true;

            worksheet.Cell(11, 1).Value = "Total Receipts:";
            worksheet.Cell(11, 2).Value = filteredReceipts.Count;

            worksheet.Cell(12, 1).Value = "Total Net Amount:";
            worksheet.Cell(12, 2).Value = filteredReceipts.Sum(r => r.NetAmount);
            worksheet.Cell(12, 2).Style.NumberFormat.Format = "#,##0.00";

            worksheet.Cell(13, 1).Value = "Total Tax Amount:";
            worksheet.Cell(13, 2).Value = filteredReceipts.Sum(r => r.TotalTaxAmount);
            worksheet.Cell(13, 2).Style.NumberFormat.Format = "#,##0.00";

            worksheet.Cell(14, 1).Value = "Total Gross Amount:";
            worksheet.Cell(14, 2).Value = filteredReceipts.Sum(r => r.TotalAmount);
            worksheet.Cell(14, 2).Style.NumberFormat.Format = "#,##0.00";

            // Grand Total
            worksheet.Cell(16, 1).Value = "Grand Total Tax Collected:";
            worksheet.Cell(16, 1).Style.Font.Bold = true;
            worksheet.Cell(16, 1).Style.Font.FontSize = 12;
            worksheet.Cell(16, 2).Value = filteredInvoices.Sum(i => i.TotalTaxAmount) + filteredReceipts.Sum(r => r.TotalTaxAmount);
            worksheet.Cell(16, 2).Style.NumberFormat.Format = "#,##0.00";
            worksheet.Cell(16, 2).Style.Font.Bold = true;
            worksheet.Cell(16, 2).Style.Fill.BackgroundColor = XLColor.LightYellow;

            worksheet.Columns().AdjustToContents();

            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            return stream.ToArray();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating tax summary report");
            throw;
        }
    }

    public async Task<byte[]> GenerateSalesAnalysisReportAsync(
        SalesAnalysisOptions options,
        CancellationToken cancellationToken = default)
    {
        try
        {
            _logger.LogInformation("Generating sales analysis report");

            var invoices = await _unitOfWork.Invoices.GetAllAsync();
            var receipts = await _unitOfWork.Receipts.GetAllAsync();

            var filteredInvoices = invoices
                .Where(i => i.DateTimeIssued >= options.StartDate && i.DateTimeIssued <= options.EndDate)
                .ToList();

            var filteredReceipts = receipts
                .Where(r => r.DateTimeIssued >= options.StartDate && r.DateTimeIssued <= options.EndDate)
                .ToList();

            using var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Sales Analysis");

            worksheet.Cell(1, 1).Value = "Sales Analysis Report";
            worksheet.Cell(1, 1).Style.Font.Bold = true;
            worksheet.Cell(1, 1).Style.Font.FontSize = 16;

            worksheet.Cell(2, 1).Value = $"Period: {options.StartDate:yyyy-MM-dd} to {options.EndDate:yyyy-MM-dd}";

            // Daily breakdown
            worksheet.Cell(4, 1).Value = "Date";
            worksheet.Cell(4, 2).Value = "B2B Sales";
            worksheet.Cell(4, 3).Value = "B2C Sales";
            worksheet.Cell(4, 4).Value = "Total Sales";
            worksheet.Range(4, 1, 4, 4).Style.Font.Bold = true;
            worksheet.Range(4, 1, 4, 4).Style.Fill.BackgroundColor = XLColor.LightBlue;

            var dailyData = filteredInvoices
                .GroupBy(i => i.DateTimeIssued.Date)
                .Select(g => new
                {
                    Date = g.Key,
                    B2BSales = g.Sum(i => i.TotalAmount),
                    B2CSales = filteredReceipts
                        .Where(r => r.DateTimeIssued.Date == g.Key)
                        .Sum(r => r.TotalAmount)
                })
                .OrderBy(x => x.Date)
                .ToList();

            int row = 5;
            foreach (var day in dailyData)
            {
                worksheet.Cell(row, 1).Value = day.Date.ToString("yyyy-MM-dd");
                worksheet.Cell(row, 2).Value = day.B2BSales;
                worksheet.Cell(row, 3).Value = day.B2CSales;
                worksheet.Cell(row, 4).Value = day.B2BSales + day.B2CSales;
                row++;
            }

            worksheet.Column(2).Style.NumberFormat.Format = "#,##0.00";
            worksheet.Column(3).Style.NumberFormat.Format = "#,##0.00";
            worksheet.Column(4).Style.NumberFormat.Format = "#,##0.00";

            worksheet.Columns().AdjustToContents();

            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            return stream.ToArray();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating sales analysis report");
            throw;
        }
    }
}
